### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mhsjlw** [SopaXorzTaker/pe-proxy#1]
What's the license for this code?

**Comment by SopaXorzTaker** [comment]
I have not decided yet, and as you can see this project is abandoned and probably won't get any updates. Why are you interested though?

**Comment by mhsjlw** [comment]
I was interested in the RakNet portion of this software. Unfortunately, GPLv3 won't work for me. Thank you for responding, though.

**Comment by SopaXorzTaker** [comment]
The RakNet portion was pretty much hacked together. It didn't even work properly IIRC.
